name: detectron2_search_xray
environment:
    image: "determinedai/example-detectron2:0.6-cuda-10.2-pytorch-1.10"
hyperparameters:
  global_batch_size: 8
  model_yaml:
      type: categorical
      vals: ['models/fast_rcnn_R_50_FPN_1x.yaml','models/mask_rcnn_R_50_FPN_noaug_1x.yaml','cascade_mask_rcnn_R_50_FPN_3x.yaml']
  dataset_name: 'x-ray-rheumatology'
  output_dir: None
  fake_data: False
searcher:
  name: grid
  metric: bboxAP
  max_length: 
    batches: 9000
  smaller_is_better: false
resources:
    slots_per_trial: 4
entrypoint: model_def:DetectronTrial
max_restarts: 0
min_validation_period:
  batches: 100
